### ISSUE TITLE
AllOverIt.Extensions.DoubleExtensions remove Epsilon

### ISSUE THREAD

**Issue by TimeTravelPenguin** [mjfreelancing/AllOverIt#3]
At current, the DoubleExtensions class has a defined constant `const double Epsilon = 1E-07`.
I propose removing it to use the build-in `double.Epsilon`, then adding overloads to allow for custom variance, which seems to be the more modern approach in many other libraries.

[This old post](https://stackoverflow.com/a/2411661/10691106) on StackOverflow describes that:
> The `System.Double` type can represent values accurate to up to 15 digits. So a simple first order estimate if a double value `x `is equal to some constant is to use an epsilon of constant * 1E-15

Another post on the same thread suggests their own implementation, should you wish to keep a default variance:
```cs
/// <summary>
/// smallest such that 1.0+EpsilonD != 1.0
/// </summary>
public const double EpsilonD = 2.2204460492503131e-016;
```

**Comment by mjfreelancing** [comment]
If you take a look at https://docs.microsoft.com/en-us/dotnet/api/system.double.epsilon?view=net-5.0 there are a couple of important comments:

`The value of the Epsilon property is not equivalent to machine epsilon, which represents the upper bound of the relative error due to rounding in floating-point arithmetic.`

and

`Two apparently equivalent floating-point numbers might not compare equal because of differences in their least significant digits. For example, the C# expression, (double)1/3 == (double)0.33333, does not compare equal because the division operation on the left side has maximum precision while the constant on the right side is precise only to the specified digits. If you create a custom algorithm that determines whether two floating-point numbers can be considered equal, we do not recommend that you base your algorithm on the value of the Epsilon constant to establish the acceptable absolute margin of difference for the two values to be considered equal.`

I currently use a value of `1E-7` as this suits most requirements. There's already overloads available for `IsZero()` and `IsEqualTo()` that allow a custom tolerance to be provided.
