### ISSUE TITLE
AllOverIt.EntityFrameworkCore.Diagrams Does Not Work With The .NET Options Pattern

### ISSUE THREAD

**Issue by EmperorArthur** [mjfreelancing/AllOverIt#95]
**Describe the bug**
.NET uses the [Options Pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options) to provide configuration.

The `D2ErdGenerator` constructor requires an "ErdOptions" class.  However, it does not accept an `IOptions<ErdOptions>` or similar.  This means that it cannot be instantiated by dependency injection without hacks.

**To Reproduce**
* Add the AllOverIt.EntityFrameworkCore.Diagrams package.
* Use the default options: `builder.Services.Configure<ErdOptions>(options => {});`
* Register the service  `builder.Services.AddSingleton(D2ErdGenerator)();`
* Add an endpoint `app.MapGet("/DbDiagram", (D2ErdGenerator generator, MyDbContext dbContext) => generator.Generate(dbContext));`

**Expected behavior**
The ERD string is generated.

** Actual behavior**
Crashes.

**Additional context**
This can be hacked around with the following: `builder.Services.AddTransient( serviceProvider => serviceProvider.GetRequiredService<IOptions<ErdOptions>>().Value );`

**Comment by mjfreelancing** [comment]
There's several reasons why direct support for the options pattern is not provided in AllOverIt.

1. The biggest reason is that all packages would require an additional dependency on microsoft.extensions.options

2. Consider other classes, such as `RsaEncryptor` in AllOverIt.Cryptography, that have multiple constructors. It just isn't plausable to add more constructors to cover all of the different combinations, with and without `IOptions<T>`.

3. Since your application is already using `IOptions<T>`, you could simply add this extension method:

```
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddD2ErdGenerator(this IServiceCollection services)
    {
        services.AddSingleton(provider => {
            var options = provider.GetRequiredService<IOptions<ErdOptions>>().Value;
            return new D2ErdGenerator(options);
        });

        return services;
    }
}
```

And call it using:

```
services.AddD2ErdGenerator();
```

4. If the above is too much, then simply replace:

```
builder.Services.AddSingleton<D2ErdGenerator>();
```

With

```
services.AddSingleton(provider => {
  var options = provider.GetRequiredService<IOptions<ErdOptions>>().Value;
  return new D2ErdGenerator(options);
});
```

5. Another alternative would be to create a factory, for the case where you want to be able to mock the generator in a test:

```
public interface ID2ErdGeneratorFactory
{
    D2ErdGenerator Create();
}

internal sealed class D2ErdGeneratorFactory : ID2ErdGeneratorFactory
{
    private readonly ErdOptions _options;

    public D2ErdGeneratorFactory(IOptions<ErdOptions> options)
    {
        _options = options.Value.WhenNotNull();    
    }

    public D2ErdGenerator Create()
    {
        return new D2ErdGenerator(_options);
    }
}
```

And then use this alternative extension method:

```
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddD2ErdGenerator(this IServiceCollection services)
    {
        services.AddSingleton<ID2ErdGeneratorFactory, D2ErdGeneratorFactory>();

        return services;
    }
}
```

In your example, you would of course have to inject `ID2ErdGeneratorFactory` instead, and call its `Create()` method to get the generator instance.

In my opinion, use of the options pattern is more of an application-level decision. And, if used, it's simple enough to make extension methods so everything works as required.

Are you aware of any other large libraries that provide direct support for use of `IOptions<T>` ?
